### ISSUE TITLE
onClick in swiper doesn't act as expected, loop option true

### ISSUE THREAD

**Issue by windht** [nickpisacane/react-dynamic-swiper#26] opened 2019-04-29 16:24 UTC
Below is the code.

```
<Swiper
          swiperOptions={{
            slidesPerView: 7,
            loop: true,
            direction: "vertical"
          }}
        >
          {this.props.categories.map(category => {
            return (
              <Slide>
                <div
                  onClick={() => {
                    this.selectCategory(category);
                  }}
                >
                  <div>{category}</div>
                </div>
              </Slide>
            );
          })}
</Swiper>
```

I also checked for some related issues but no luck. Are there any props I can solid bind onClick to?

**Comment by nickpisacane** [comment] 2019-05-30 17:46
@windht Is this an issue with react-dynamic-swiper? It doesn't seem like it would be, but if you could provide link to an codesandbox of a reproducable instance of this error, that would be much appreciated.

**Comment by nickpisacane** [comment] 2019-05-30 18:14
@windht So the problem is that you are passing `loop: true` in the `swiperOptions` object. If you check the logs, there should be a warning. Sorry, the documentation for this needs to be better and in reality react-dynamic-swiper should probably be throwing an error for that, but it is a tricky issue due to backwards compatibility. So, next rollout will probably make things a little more clear. For this instance, you should remove the `loop: true`, and provide a `loop={true}` prop directly to <Swiper />. Here's a link to a codesandbox where I demonstrate what you are trying to accomplish (in general): [Demo](https://codesandbox.io/s/cool-frost-cqc6j).

Going to close this for now, but feel free to re-open if this is something more than an issue of not using the loop prop.

**Closed by nickpisacane** 2019-05-30 18:14 UTC
Labels: question

**Comment by windht** [comment] 2019-05-31 14:02
@nickpisacane Sorry for not providing a sample together with the issue. But thanks a lot! The `loop={true}` did the trick!
